const level = [
{
"Level": 0,
"exp": 0,
"Experience Needed for Next Level": 1000,
"Proficiency Bonus": "+1",
"Stress per Exhaustion": 1,
"Specialty Die": "-",
"Ability Score Improvement": "-",
"Base Mana": "-",
"Mana at Mind Down": "-",
"Max Spell Level": 0,
"Concentration DC at Mind Down": 8,
"Spell Level Cost": 1
},
{
"Level": 1,
"exp": 1000,
"Experience Needed for Next Level": 2000,
"Proficiency Bonus": "+2",
"Stress per Exhaustion": 2,
"Specialty Die": "d4",
"Ability Score Improvement": "",
"Base Mana": 4,
"Mana at Mind Down": 2,
"Max Spell Level": 1,
"Concentration DC at Mind Down": 9,
"Spell Level Cost": 2
},
{
"Level": 2,
"exp": 3000,
"Experience Needed for Next Level": 3000,
"Proficiency Bonus": "+2",
"Stress per Exhaustion": 2,
"Specialty Die": "d4",
"Ability Score Improvement": "",
"Base Mana": 8,
"Mana at Mind Down": 4,
"Max Spell Level": 1,
"Concentration DC at Mind Down": 9,
"Spell Level Cost": 2
},
{
"Level": 3,
"exp": 6000,
"Experience Needed for Next Level": 4000,
"Proficiency Bonus": "+2",
"Stress per Exhaustion": 2,
"Specialty Die": "d4",
"Ability Score Improvement": "",
"Base Mana": 14,
"Mana at Mind Down": 6,
"Max Spell Level": 2,
"Concentration DC at Mind Down": 10,
"Spell Level Cost": 4
},
{
"Level": 4,
"exp": 10000,
"Experience Needed for Next Level": 5000,
"Proficiency Bonus": "+2",
"Stress per Exhaustion": 2,
"Specialty Die": "d4",
"Ability Score Improvement": "ASI",
"Base Mana": 18,
"Mana at Mind Down": 8,
"Max Spell Level": 2,
"Concentration DC at Mind Down": 10,
"Spell Level Cost": 4
},
{
"Level": 5,
"exp": 15000,
"Experience Needed for Next Level": 5000,
"Proficiency Bonus": "+3",
"Stress per Exhaustion": 3,
"Specialty Die": "d6",
"Ability Score Improvement": "",
"Base Mana": 34,
"Mana at Mind Down": 15,
"Max Spell Level": 3,
"Concentration DC at Mind Down": 11,
"Spell Level Cost": 8
},
{
"Level": 6,
"exp": 20000,
"Experience Needed for Next Level": 5000,
"Proficiency Bonus": "+3",
"Stress per Exhaustion": 3,
"Specialty Die": "d6",
"Ability Score Improvement": "",
"Base Mana": 42,
"Mana at Mind Down": 18,
"Max Spell Level": 3,
"Concentration DC at Mind Down": 11,
"Spell Level Cost": 8
},
{
"Level": 7,
"exp": 25000,
"Experience Needed for Next Level": 5000,
"Proficiency Bonus": "+3",
"Stress per Exhaustion": 3,
"Specialty Die": "d6",
"Ability Score Improvement": "",
"Base Mana": 54,
"Mana at Mind Down": 21,
"Max Spell Level": 4,
"Concentration DC at Mind Down": 12,
"Spell Level Cost": 12
},
{
"Level": 8,
"exp": 30000,
"Experience Needed for Next Level": 6000,
"Proficiency Bonus": "+3",
"Stress per Exhaustion": 3,
"Specialty Die": "d6",
"Ability Score Improvement": "ASI",
"Base Mana": 66,
"Mana at Mind Down": 24,
"Max Spell Level": 4,
"Concentration DC at Mind Down": 12,
"Spell Level Cost": 12
},
{
"Level": 9,
"exp": 36000,
"Experience Needed for Next Level": 7000,
"Proficiency Bonus": "+4",
"Stress per Exhaustion": 4,
"Specialty Die": "d8",
"Ability Score Improvement": "",
"Base Mana": 86,
"Mana at Mind Down": 36,
"Max Spell Level": 5,
"Concentration DC at Mind Down": 13,
"Spell Level Cost": 20
},
{
"Level": 10,
"exp": 43000,
"Experience Needed for Next Level": 8000,
"Proficiency Bonus": "+4",
"Stress per Exhaustion": 4,
"Specialty Die": "d8",
"Ability Score Improvement": "",
"Base Mana": 106,
"Mana at Mind Down": 40,
"Max Spell Level": 5,
"Concentration DC at Mind Down": 13,
"Spell Level Cost": 20
},
{
"Level": 11,
"exp": 51000,
"Experience Needed for Next Level": 9000,
"Proficiency Bonus": "+4",
"Stress per Exhaustion": 4,
"Specialty Die": "d8",
"Ability Score Improvement": "",
"Base Mana": 121,
"Mana at Mind Down": 44,
"Max Spell Level": "6*",
"Concentration DC at Mind Down": 14,
"Spell Level Cost": 30
},
{
"Level": 12,
"exp": 60000,
"Experience Needed for Next Level": 10000,
"Proficiency Bonus": "+4",
"Stress per Exhaustion": 4,
"Specialty Die": "d8",
"Ability Score Improvement": "ASI",
"Base Mana": 136,
"Mana at Mind Down": 48,
"Max Spell Level": "6**",
"Concentration DC at Mind Down": 14,
"Spell Level Cost": 30
},
{
"Level": 13,
"exp": 70000,
"Experience Needed for Next Level": 12000,
"Proficiency Bonus": "+5",
"Stress per Exhaustion": 5,
"Specialty Die": "d10",
"Ability Score Improvement": "",
"Base Mana": 158,
"Mana at Mind Down": 65,
"Max Spell Level": "7*",
"Concentration DC at Mind Down": 15,
"Spell Level Cost": 45
},
{
"Level": 14,
"exp": 82000,
"Experience Needed for Next Level": 14000,
"Proficiency Bonus": "+5",
"Stress per Exhaustion": 5,
"Specialty Die": "d10",
"Ability Score Improvement": "",
"Base Mana": 180,
"Mana at Mind Down": 70,
"Max Spell Level": "7**",
"Concentration DC at Mind Down": 15,
"Spell Level Cost": 45
},
{
"Level": 15,
"exp": 96000,
"Experience Needed for Next Level": 16000,
"Proficiency Bonus": "+5",
"Stress per Exhaustion": 5,
"Specialty Die": "d10",
"Ability Score Improvement": "",
"Base Mana": 210,
"Mana at Mind Down": 75,
"Max Spell Level": "8*",
"Concentration DC at Mind Down": 16,
"Spell Level Cost": 60
},
{
"Level": 16,
"exp": 112000,
"Experience Needed for Next Level": 18000,
"Proficiency Bonus": "+5",
"Stress per Exhaustion": 5,
"Specialty Die": "d10",
"Ability Score Improvement": "ASI",
"Base Mana": 240,
"Mana at Mind Down": 80,
"Max Spell Level": "8**",
"Concentration DC at Mind Down": 16,
"Spell Level Cost": 60
},
{
"Level": 17,
"exp": 130000,
"Experience Needed for Next Level": 20000,
"Proficiency Bonus": "+6",
"Stress per Exhaustion": 6,
"Specialty Die": "d12",
"Ability Score Improvement": "",
"Base Mana": 285,
"Mana at Mind Down": 102,
"Max Spell Level": "9*",
"Concentration DC at Mind Down": 17,
"Spell Level Cost": 90
},
{
"Level": 18,
"exp": 150000,
"Experience Needed for Next Level": 20000,
"Proficiency Bonus": "+6",
"Stress per Exhaustion": 6,
"Specialty Die": "d12",
"Ability Score Improvement": "",
"Base Mana": 330,
"Mana at Mind Down": 108,
"Max Spell Level": "9*",
"Concentration DC at Mind Down": 17,
"Spell Level Cost": 90
},
{
"Level": 19,
"exp": 170000,
"Experience Needed for Next Level": 30000,
"Proficiency Bonus": "+6",
"Stress per Exhaustion": 6,
"Specialty Die": "d12",
"Ability Score Improvement": "",
"Base Mana": 375,
"Mana at Mind Down": 114,
"Max Spell Level": "9*",
"Concentration DC at Mind Down": 17,
"Spell Level Cost": 90
},
{
"Level": 20,
"exp": 200000,
"Experience Needed for Next Level": "",
"Proficiency Bonus": "+6",
"Stress per Exhaustion": 6,
"Specialty Die": "d12",
"Ability Score Improvement": "ASI",
"Base Mana": 420,
"Mana at Mind Down": 120,
"Max Spell Level": "9**",
"Concentration DC at Mind Down": 17,
"Spell Level Cost": 90
}
]

export default level;